Add comment to PR if the diff fails

diff --git a/.github/workflows/check-dist.yml b/.github/workflows/check-dist.yml
--- a/.github/workflows/check-dist.yml
+++ b/.github/workflows/check-dist.yml
@@ -26,8 +26,26 @@ jobs:
       - name: Compare the expected and actual dist/ directories
         id: diff
         run: |
-          if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
+          if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; 
+          then
             echo "Detected uncommitted changes after build.  See status below:"
             git diff
-            exit 1
+
+            echo '::set-output name=failure::true'
+          else
+            echo '::set-output name=failure::false'
           fi
+
+      - name: Post information to the PR if it fails
+        uses: mshick/add-pr-comment@v1
+        if: ${{ steps.diff.outputs.failure }} == true
+        with:
+          message: |
+            Did you forget to add the dist folder? 
+            Please run "npm run build", and commit the dist/ folder.
+          repo-token: ${{ secrets.DIGNIO_GH_APP_PRIVATE_KEY }}
+          repo-token-user-login: 'github-actions[bot]'
+
+      - name: Exit if failure
+        if: ${{ steps.diff.outputs.failure }} == true
+        run: exit 1
